### ISSUE TITLE
Finish the Create Device popup

### ISSUE THREAD

**Issue by nbiton** [nbiton/IoThingies#6]
Needs to have a handler which creates a new device documents

**Comment by Nexus7** [comment]
Should this have 'test the new device' at the end of the setup procedure? better to validate the device at the time it is being set up and do all the connection debugging at that time? So I would say the 'Add new device' could be something like this:

1) Choose from a selection of sample devices (eg, Spark, Arduino, Pi, or CUSTOM - Prompt for name)
2) Choose from 'device pushes data to cloud & iothingies pulls data from cloud' or 'device sends data direct to iothingies' [maybe just assume the first option for now until we get the push confirmed for particle at least]
3) If 'iothingies pulls data' chosen then maybe a small blurb about what to do for that device... so for particle could be 'Please ensure that you add the code 'Particle.variable....' to your firmware sketch.
4) If 'device sends data direct to iothingies' chosen then if device is known about then can provide the sample code for that device (eg, C code for Particle/Arduino, Python/Bash code for Pi)
5) Test your device now dialog

**Comment by nbiton** [comment]
I think we need to find a way how to support the same kind of stuff for arduino and Pi which spark has.
Probably a simple library for each to register the variables and functions which would push data to our server instead of needing to pull it by the sampler.

I believe each should have an issue page of its own, as well as the initial test feature.
Unless if we can think of a simple way to achieve it quickly, we should aim to get these done after we're finished with all the '_MVP_' issues

**Comment by nbiton** [comment]
Looks to me that it closes this one, the other stuff have their own issues now.
